# Generated by Django 4.1.7 on 2023-05-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('p_image', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=255)),
                ('accident_id', models.CharField(max_length=255)),
                ('total_price', models.CharField(max_length=255)),
                ('closed_date', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'claim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('p_image', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('admin_id', models.IntegerField()),
                ('is_active', models.CharField(db_column='is_Active', max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'expert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_approved', models.CharField(db_column='is_Approved', max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'garage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GarageBid',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'garage_bid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthContract',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('contract_type', models.CharField(max_length=255)),
                ('contract_price', models.CharField(max_length=255)),
                ('contract_date', models.CharField(max_length=255)),
                ('expire_date', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'health_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'hospitals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreviousAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_date', models.CharField(max_length=255)),
                ('vehicle_damage', models.CharField(max_length=255)),
                ('personal_claims', models.CharField(max_length=255)),
                ('property_damage', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'previous_accident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proposer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('p_image', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'proposer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treat',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'treat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('engine_number', models.CharField(db_column='Engine_number', max_length=255)),
                ('chassis_number', models.CharField(max_length=255)),
                ('owner_f_name', models.CharField(max_length=255)),
                ('owner_l_name', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('body_type', models.CharField(max_length=255)),
                ('horse_power', models.CharField(max_length=255)),
                ('good_capacity', models.CharField(max_length=255)),
                ('passenger_capacity', models.CharField(max_length=255)),
                ('bsg_action', models.CharField(db_column='BSG_action', max_length=255)),
                ('cover_required', models.CharField(max_length=255)),
                ('drivers_covered', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleContract',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('contract_type', models.CharField(max_length=255)),
                ('contract_price', models.CharField(max_length=255)),
                ('contract_date', models.CharField(max_length=255)),
                ('expire_date', models.CharField(max_length=255)),
                ('is_approved', models.CharField(db_column='is_Approved', max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'vehicle_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('proposer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ais.proposer')),
                ('subcity', models.CharField(max_length=255)),
                ('woreda', models.CharField(max_length=255)),
                ('kebele', models.CharField(max_length=255)),
                ('house_no', models.CharField(max_length=255)),
                ('p_o_box', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'business_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraFitting',
            fields=[
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ais.vehicle')),
                ('radio', models.CharField(max_length=255)),
                ('communication', models.CharField(max_length=255)),
                ('bsd', models.CharField(db_column='BSD', max_length=255)),
            ],
            options={
                'db_table': 'extra_fitting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemGaragePrice',
            fields=[
                ('garage_bid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ais.garagebid')),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'item_garage_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsList',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ais.bid')),
                ('item_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'items_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtherInsurances',
            fields=[
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ais.vehicle')),
                ('cancel', models.CharField(max_length=255)),
                ('decline', models.CharField(max_length=255)),
                ('iae', models.CharField(max_length=255)),
                ('isc', models.CharField(max_length=255)),
                ('refuse', models.CharField(max_length=255)),
                ('requires', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'other_insurances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResidentialAddress',
            fields=[
                ('proposer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ais.proposer')),
                ('subcity', models.CharField(max_length=255)),
                ('woreda', models.CharField(max_length=255)),
                ('kebele', models.CharField(max_length=255)),
                ('house_no', models.CharField(max_length=255)),
                ('p_o_box', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'residential_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TreatDocuments',
            fields=[
                ('treat', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ais.treat')),
                ('document', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'treat_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ais.vehicle')),
                ('images', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vehicle_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehiclePlate',
            fields=[
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ais.vehicle')),
                ('code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vehicle_plate',
                'managed': False,
            },
        ),
    ]
