# Generated by Django 4.1.7 on 2023-06-07 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('road_type', models.CharField(max_length=255)),
                ('vehicle_speed', models.CharField(max_length=255)),
                ('traffic_signal', models.CharField(max_length=255)),
                ('road_side_far', models.CharField(max_length=255)),
                ('injured_people_number', models.CharField(max_length=255)),
                ('death_number', models.CharField(max_length=255)),
                ('cost_estimation', models.CharField(max_length=255)),
                ('f_name', models.CharField(db_column='F_NAME', max_length=255)),
            ],
            options={
                'db_table': 'accident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('p_image', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('subcity', models.CharField(max_length=255)),
                ('woreda', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=255)),
                ('kebele', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('isappoved', models.CharField(db_column='isAppoved', max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InjuredPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injurytype', models.CharField(max_length=255)),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'injured_people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvolvedVehicle',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('driver_f_name', models.CharField(max_length=255)),
                ('driver_l_name', models.CharField(max_length=255)),
                ('owner_f_name', models.CharField(max_length=255)),
                ('owner_l_name', models.CharField(max_length=255)),
                ('driver_license_number', models.CharField(max_length=255)),
                ('driver_phone', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'involved_vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('p_image', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'traffic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccidentImages',
            fields=[
                ('accident', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='traffic.accident')),
                ('image_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'accident_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('accident', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='traffic.accident')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=255)),
                ('subcity', models.CharField(max_length=255)),
                ('woreda', models.CharField(max_length=255)),
                ('kebele', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvolvedVehiclePlate',
            fields=[
                ('involved_vehicle', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='traffic.accident')),
                ('code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'involved_vehicle_plate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeoplesInInvolvedVehicle',
            fields=[
                ('involved_vehicle', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='traffic.involvedvehicle')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'peoples_in_involved_vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlateNumber',
            fields=[
                ('accident', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='traffic.accident')),
                ('code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'plate_number',
                'managed': False,
            },
        ),
    ]
